### PR TITLE
Rebase (via merge) to bring up to date with videojs

### PR DESCRIPTION
**Pull request by Rarian**

### CODE REVIEW

**Comment by Rarian** [comment]
Closing this as it doesn't actually work.  Will re-open if I can get mp3 playback to work.

**Comment by rdgRmCore** [comment]
@Rarian What exactly are you trying to do? I had mp3 playback working several months ago. It never got merged into the upstream repo. I assume at this point that there have been conflicting changes made.

**Comment by Rarian** [comment]
I was trying to bring your changes up to date with upstream, to allow it to hopefully be merged in.  Unfortunately a straightforward update breaks mp3 support (at least in my local tests.)

Would you be able to tell me what version of video.js you were able to get mp3 playback working with?

**Comment by rdgRmCore** [comment]
@Rarian,
I am not sure how to answer your question. 
Looks like the last commit before I made a fork was:

0.10.4 of the videojs-contrib-hls branch

https://github.com/rdgRmCore/videojs-contrib-hls/commit/e686ddde77f28fc6ccc0a3ae23b449c2b0a177ec

**Pull request closed without merging**
